FROM us-docker.pkg.dev/vertex-ai/training/tf-gpu.2-6:latest

WORKDIR /root

#RUN pip install google-cloud-pipeline-components==0.1.7 google-cloud-aiplatform google-cloud-storage

# Copies the trainer code to the docker image.
COPY . /root/

ENTRYPOINT ["python3", "pipeline_execute.py"]
